export const INHABITANTS_MAP: Record<string, string> = {
  "Gesamte Schweiz": "Schweizerinnen und Schweizer",
  "Zürich": "Zürcherinnen und Zürcher",
  "Bern": "Bernerinnen und Berner",
  "Waadt": "Waadtländerinnen und Waadtländer",
  "Aargau": "Aargauerinnen und Aargauer",
  "St. Gallen": "St. Gallerinnen und St. Galler",
  "Genf": "Genferinnen und Genfer",
  "Luzern": "Luzernerinnen und Luzerner",
  "Tessin": "Tessinerinnen und Tessiner",
  "Wallis": "Walliserinnen und Walliser",
  "Freiburg": "Freiburgerinnen und Freiburger",
  "Basel-Landschaft": "Baselbieterinnen und Baselbieter",
  "Solothurn": "Solothurnerinnen und Solothurner",
  "Thurgau": "Thurgauerinnen und Thurgauer",
  "Graubünden": "Bündnerinnen und Bündner",
  "Neuenburg": "Neuenburgerinnen und Neuenburger",
  "Basel-Stadt": "Baslerinnen und Basler",
  "Schwyz": "Schwyzerinnen und Schwyzer",
  "Zug": "Zugerinnen und Zuger",
  "Schaffhausen": "Schaffhauserinnen und Schaffhauser",
  "Jura": "Jurassierinnen und Jurassier",
  "Appenzell Ausserrhoden": "Ausserrhoderinnen und Ausserrhoder",
  "Nidwalden": "Nidwaldnerinnen und Nidwaldner",
  "Glarus": "Glarnerinnen und Glarner",
  "Obwalden": "Obwaldnerinnen und Obwaldner",
  "Appenzell Innerrhoden": "Innerrhoderinnen und Innerrhoder",
  "Uri": "Urnerinnen und Urner",
  "Basel": "Baslerinnen und Basler",
  "Lausanne": "Lausannerinnen und Lausanner",
  "Winterthur": "Winterthurerinnen und Winterthurer",
  "Lugano": "Luganesi",
  "Biel/Bienne": "Bielerinnen und Bieler",
  "Bellinzona": "Bellinzonesi",
  "Thun": "Thunerinnen und Thuner",
  "Köniz": "Könizerinnen und Könizer",
  "Fribourg/Freiburg": "Freiburgerinnen und Freiburger",
  "La Chaux-de-Fonds": "Einwohnerinnen und Einwohner",
  "Chur": "Churerinnen und Churer",
  "Sion": "Sittenerinnen und Sittener",
  "Vernier": "Einwohnerinnen und Einwohner",
  "Uster": "Ustermerinnen und Ustermer",
  "Lancy": "Einwohnerinnen und Einwohner",
  "Emmen": "Emmerinnen und Emmer",
  "Yverdon-les-Bains": "Yverdonnerinnen und Yverdonner",
  "Dübendorf": "Dübendorferinnen und Dübendorfer",
  "Kriens": "Krienserinnen und Krienser",
  "Dietikon": "Dietikerinnen und Dietiker",
  "Montreux": "Einwohnerinnen und Einwohner",
  "Frauenfeld": "Frauenfelderinnen und Frauenfelder",
  "Wetzikon": "Wetzikerinnen und Wetziker",
  "Meyrin": "Einwohnerinnen und Einwohner",
  "Wil": "Wilerinnen und Wiler",
  "Baar": "Baarerinnen und Baarer",
  "Bulle": "Einwohnerinnen und Einwohner",
  "Renens": "Einwohnerinnen und Einwohner",
  "Carouge": "Einwohnerinnen und Einwohner",
  "Aarau": "Aarauerinnen und Aarauer",
  "Riehen": "Riehenerinnen und Riehener",
  "Nyon": "Nyonnerinnen und Nyonner",
  "Allschwil": "Allschwilerinnen und Allschwiler",
  "Kreuzlingen": "Kreuzlingerinnen und Kreuzlinger",
  "Horgen": "Horgnerinnen und Horgner",
  "Wettingen": "Wettingerinnen und Wettinger",
  "Kloten": "Klotenerinnen und Klotener",
  "Vevey": "Einwohnerinnen und Einwohner",
  "Schlieren": "Schlieremerinnen und Schlieremer",
  "Baden": "Badenerinnen und Badener",
  "Onex": "Einwohnerinnen und Einwohner",
  "Regensdorf": "Regensdorferinnen und Regensdorfer",
  "Adliswil": "Adliswilerinnen und Adliswiler",
  "Volketswil": "Volketswilerinnen und Volketswiler",
  "Pully": "Einwohnerinnen und Einwohner",
  "Monthey": "Einwohnerinnen und Einwohner",
  "Olten": "Oltnerinnen und Oltner",
  "Gossau": "Gossauerinnen und Gossauer",
  "Thalwil": "Thalwilerinnen und Thalwiler",
  "Reinach": "Reinacherinnen und Reinacher",
  "Illnau-Effretikon": "Illnau-Effretikerinnen und Illnau-Effretiker",
  "Ostermundigen": "Ostermundigerinnen und Ostermundiger",
  "Muttenz": "Muttenzerinnen und Muttenzer",
  "Grenchen": "Grenchnerinnen und Grenchner",
  "Steffisburg": "Steffisburgerinnen und Steffisburger",
  "Locarno": "Locarnesi",
  "Morges": "Einwohnerinnen und Einwohner",
  "Pratteln": "Prattlerinnen und Prattler",
  "Burgdorf": "Burgdorferinnen und Burgdorfer",
  "Wallisellen": "Wallisellerinnen und Walliseller",
  "Freienbach": "Freienbacherinnen und Freienbacher",
  "Wohlen": "Wohlenerinnen und Wohlener",
  "Herisau": "Herisauerinnen und Herisauer",
  "Arbon": "Arbonerinnen und Arboner",
  "Langenthal": "Langenthalerinnen und Langenthaler",
  "Mendrisio": "Mendrisinesi",
  "Einsiedeln": "Einsiedlerinnen und Einsiedler",
  "Lyss": "Lysserinnen und Lysser",
  "Meilen": "Meilemerinnen und Meilemer",
  "Binningen": "Binningerinnen und Binninger",
  "Thônex": "Einwohnerinnen und Einwohner",
  "Amriswil": "Amriswilerinnen und Amriswiler",
  "Liestal": "Liestalerinnen und Liestaler",
  "Richterswil": "Richterswilerinnen und Richterswiler",
  "Rheinfelden": "Rheinfelderinnen und Rheinfelder",
  "Horw": "Horwerinnen und Horwer",
  "Ebikon": "Ebikonerinnen und Ebikoner",
  "Uzwil": "Uzwilerinnen und Uzwiler",
  "Spreitenbach": "Spreitenbacherinnen und Spreitenbacher",
  "Altstätten": "Altstätterinnen und Altstätter",
  "Rapperswil-Jona": "Rapperswil-Jonerinnen und Rapperswil-Joner",
  "Wädenswil": "Wädenswilerinnen und Wädenswiler",
  "Bülach": "Bülacherinnen und Bülacher",
  "Hinwil": "Hinwilerinnen und Hinwiler",
  "Sierre": "Einwohnerinnen und Einwohner",
  "Stäfa": "Stäfnerinnen und Stäfner",
  "Oftringen": "Oftringerinnen und Oftringer",
  "Küssnacht": "Küssnachterinnen und Küssnachter",
  "Brig-Glis": "Einwohnerinnen und Einwohner",
  "Ecublens": "Einwohnerinnen und Einwohner",
  "Versoix": "Einwohnerinnen und Einwohner",
  "Muri bei Bern": "Murianerinnen und Murianer",
  "Münchenstein": "Münchensteinerinnen und Münchensteiner",
  "Rüti": "Rütnerinnen und Rütner",
  "Affoltern am Albis": "Affoltermerinnen und Affoltermer",
  "Le Grand-Saconnex": "Einwohnerinnen und Einwohner",
  "Buchs": "Buchserinnen und Buchser",
  "Prilly": "Einwohnerinnen und Einwohner",
  "Münsingen": "Münsingerinnen und Münsinger",
  "Spiez": "Spiezerinnen und Spiezer",
  "Worb": "Worberinnen und Worber",
  "Zofingen": "Zofingerinnen und Zofinger",
  "Risch": "Rischerinnen und Rischer",
  "Plan-les-Ouates": "Einwohnerinnen und Einwohner",
  "Weinfelden": "Weinfelderinnen und Weinfelder",
  "Estavayer": "Einwohnerinnen und Einwohner",
  "Sursee": "Surseerinnen und Surseer",
  "Birsfelden": "Birsfeldenerinnen und Birsfeldener",
  "Stans": "Stänserinnen und Stänser",
  "Nidau": "Nidauerinnen und Nidauer",
}

export function getInhabitants(regionNames: string[]): string {
  if (regionNames.length !== 1) return 'Stimmberechtigte'
  const name = regionNames[0]
  return INHABITANTS_MAP[name] ?? `Stimmberechtigte in ${name}`
}
